version: '2'

services:
  proxy:
    build: ./proxyDocker/
    ports:
      - 80:80
    depends_on:
      - server
    external_links:
      - server
    volumes:
      - ./logs/:/app/proxy/logs/

  server:
    build: ./serverDocker/
    volumes:
      - ./serverDocker/clonned_website/:/app/server/clonned_website
